services:
  - type: web
    name: searchstax-crawler-outcome-qa
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /healthz
    autoDeploy: true
